### ISSUE TITLE
What IS this?

### ISSUE THREAD

**Issue by foxsouns** [ninjamuffin99/mommyGF#1]
also why am i looking through your repos lmao
time to disappear i guess

but really where would i find a compiled thing lol
a site, some binaries or whatever
or instructions for for buildin or something? lol i just want some input

**Comment by ghost** [comment]
Try compiling the same way as you compile the funk

**Comment by upintheairsheep** [comment]
Close issue

**Comment by foxsouns** [comment]
> Close issue

fine then, maybe i will
